version: '3.8'

services:
  # Unified Frontend + Admin Panel
  frontend:
    build: 
      context: .
      dockerfile: Dockerfile.unified
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - lvda_network
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Backend - API
  backend:
    build: ./backend
    ports:
      - "3001:3001"  # Keep exposed for debugging if needed
    volumes:
      - database_data:/data
    networks:
      - lvda_network
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - DB_PATH=/data/contacts.db
      - PORT=3001
      - ALLOWED_ORIGINS=http://localhost:3000,http://frontend:3000
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  database_data:
    driver: local

networks:
  lvda_network:
    driver: bridge